(Get-Content nodes.py).Replace("`t","    ")
(Get-Content pacman.py).Replace("`t","    ")
(Get-Content run.py).Replace("`t","    ")
(Get-Content vector.py).Replace("`t","    ")
(Get-Content constants.py).Replace("`t","    ")